### ISSUE TITLE
Cache stats in Redis to avoid db connections

### ISSUE THREAD

**Issue by karpet** [BlueprintKansas/ksvotes.org#538]
We can leverage Redis to cache things that do not change often, like stats. This should reduce DB load and HTTP requests.

**Comment by karpet** [comment]
example of my local `docker-compose.yml` file for postgres and redis servers:

```
version: '3'
services:
  redis:
    image: redis:2.8.23
    ports:
      - "6379:6379"

  ksvotes-postgres:
    image: postgres:11.7
    container_name: ksvotes-db
    ports:
      - "5432:5432"
    volumes:
      - "postgresdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=postgres

volumes:
  postgresdata:
```

which I invoke like:

```
% docker-compose up -d
```
